// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";
// // import Navbar from "./components/Navbar";
// // import ScrollToTopButton from "./styles/ScrollToTopButton";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       > 
// //       <Navbar/>
// //         {children}
// //         <ScrollToTopButton/>
// //       </body>
// //     </html>
// //   );
// // }


// // import "./globals.css";
// // import Navbar from "./components/Navbar";
// // import ScrollToTopButton from "./styles/ScrollToTopButton";
// // // import HeroSection from "./components/HeroSections";

// // export default function RootLayout({ children }) {
// //   return (
// //     <html lang="en">

// //       <body
// //         // className="
// //         //   antialiased
// //         //   text-[#0B1C2D]
// //         //   bg-white
// //         // "
// //       >
// //      {/* <HeroSection/> */}
// //         <Navbar />

// //         {children}

// //         <ScrollToTopButton />

// //       </body>

// //     </html>
// //   );
// // }


// import "./globals.css";
// import Navbar from "./components/Navbar";
// import ScrollToTopButton from "./styles/ScrollToTopButton";

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body
//         suppressHydrationWarning
//         className="antialiased text-[#0B1C2D] bg-white"
//       >
//         <Navbar />

//         {children}

//         <ScrollToTopButton />
//       </body>
//     </html>
//   );
// }


import "./globals.css";
import Navbar from "./components/Navbar";
import ScrollToTopButton from "./styles/ScrollToTopButton";

/* ✅ ADD METADATA HERE */
export const metadata = {
  title: "Law Firm in Bangalore | S Jain Attorneys",
  description:
    "S Jain Attorneys is a leading law firm in Bangalore offering corporate, civil, criminal, family, property and advisory legal services with integrity and experience.",
  keywords: [
    "Law Firm in Bangalore",
    "Corporate Lawyer Bangalore",
    "Civil Lawyer Bangalore",
    "Criminal Lawyer Bangalore",
    "Property Lawyer Bangalore",
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased text-[#0B1C2D] bg-white">

        <Navbar />

        {children}

        <ScrollToTopButton />

      </body>
    </html>
  );
}